services:
  vectorizer:
    build: .
    env_file:
      - .env
      - /opt/blackeveryday/config/.env.common
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
    networks:
      - blackeveryday_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  blackeveryday_network:
    external: true